apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ext-proc-filter
  namespace: kserve
spec:
  workloadSelector:
    labels:
      istio.io/gateway-name: kserve-ingress-gateway
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter:
              name: "envoy.filters.http.router"
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.ext_proc
        typed_config:
          "@type": type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: "type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3.ExternalProcessor"
          value:
            failure_mode_allow: false
            message_timeout:
              seconds: 10
            processing_mode:
              request_header_mode: SEND
              request_body_mode: BUFFERED
              response_header_mode: SEND
              response_body_mode: BUFFERED
            grpc_service:
              timeout:
                seconds: 10
              # envoy_grpc:
              #   cluster_name: ext-proc-token
              google_grpc:
                target_uri: host.docker.internal:50051
                stat_prefix: token-ext-proc
  - applyTo: CLUSTER
    match:
      cluster:
        service: host.docker.internal
    patch:
      operation: ADD
      value:
        name: ext-proc-token
        type: STRICT_DNS
        connect_timeout: 1s
        http2_protocol_options: {}
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: ext-proc-token
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: host.docker.internal
                    port_value: 50051
